apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: default
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "nc.newto.uk"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nextcloud-svc
            port:
              number: 80
