---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: default
spec:
  encryptedData:
    CLOUDFLARED_TUNNEL_TOKEN: AgA1ExfkFEydm5JuF5rao3xed5v8u60sOdElesGBFpa6Wkw3Jj2ZVq6mdxGsV/kJbF17rsC/dYOyHaM7DbKkjfn61xRtv3Xb/zfwe1D6QLQXheqB3hY9iTPNiaOrrqItPZeYZAFFq2VeN0YQNgGkL2ZZkrt5YNBjjZTroZieLqiYHo44RHKBnp2p9B/QpsSLNJCcmugAt0e+u7Fxv/pnlo1KyiDxtdUVwNynG/untxndnTdrVCzb5ZU8s18eVhlCE8HTFQURhu0AVd66aDk2yiSVJd5ttSKSvTr8NEKsB3klMLXq0zTGmnzDfEFQsdbWupfYNNArftFHbuYJc9VVslu7yCg7vQ14Eid9BYqGYbURwVQcAKPKYr0YKnu6Ev1kDhGdVOHKKeYgC/2BKewdUd1eMrvuKJD/3nfD4hQsXIaCQdxrkhCIocPAMyR//RF8WbvHkvGf88pFVe0zld8JTAJkgLDOkMQTTVG6ZZubGIrHlm6YVzCn4+3wZLpdj6mDT/3DXelTC+GbrUgE8472phrt8WzaY+nJaXyb9OvY2DAKrhnxnzcgYFzVDO6rcut3TXN/1odTCrkkbf5ah+Sb4rhq2DEmGC+D9jznePofg1yZV5wKcnjILNw+xFaK9vfXFspvHtOQCAJUfpOz8BzZbuz/tehMASk0Q52s1Wa1i7vgHvyYvp8N6f2PxT5weptawm65pEo/8rGhSoamHSdeWxq0aB3qMfEaAdVyG00I+MUcsphTt08MMAjUs3u/43Sa8TWjwtEJSGLjwaaXg6faD8R19ttVbyh6u2Bdidxs+tI4sR5j1EZ8BnxeJMNId5eXFbx/c8pQYYIWRkNjf9wE5cQ1b++x/Thng9MkwJp214iz219eq5u6t/nvozOgr6i3uWjm3h9UM8lobx/aLMNnoJLmhf9AJZ8TS0pWKAuC1NPJmJjai+MUUUpe
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: default
    type: Opaque
